Olx clone
SashaLesik/Learn_pyhton_site_clon pull request #10
Opened 2024-01-04 14:43 UTC by oltanik

2024-01-05 15:01 UTC, skeapskeap reviewed
и с папкой Новая папка надо что-нибудь сделать

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
> +def parser_adt(data, count_error):
функция должна принимать на вход уже готовый url
и я не вижу смысла держать цикл внутри этой функции, пусть лучше она сама будет вызываться из цикла
аргумент count_error мне непонятен. можно же его объявлять внутри функции
```suggestion
def parser_adt(card_url, count_error):
```

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
> +            print(f'!!!!!!!!!!!!!!!!Объявление!!!!!!!!!!!!!!!!')
Функция сейчас ничего не возвращает, а должна вернуть какую-то структуру со всеми распарсенными данными, наверное словарь.

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
>      title_str = None
```suggestion
    title_previous = None
    title_current = None
```

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
>          title_begin = title_str
```suggestion
```

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
```suggestion
finally:
    title_previous = title_current
```

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
>              title_str = soup.find('title').text
```suggestion
            title_current = soup.find('title').text
```

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
>              if title_begin == title_str:
```suggestion
            if title_previous == title_current:
```

2024-01-05 15:01 UTC, skeapskeap commented on olx_parser.py
> +            parser_adt(data, count_error)
Вот в этом месте хорошо зайдёт yield
```suggestion
            parsed_adt = parser_adt(data, count_error)
            yield parsed_adt
```
Тогда функция parse_page станет генератором и можно будет делать типа такого
```python
for adt_dict in parse_page('ololo.com', 100):
    db.insert_adt(adt_dict)
```

2024-01-06 14:25 UTC, oltanik commented on olx_parser.py
> +def parser_adt(data, count_error):
Так я так сделал, чтоб не было вложенного цикла, тогда получается оставлять вложенный цикл, чтоб получать готовую ссылку? Или добавить еще одну функцию, которая будет с циклом в котором получается готовая ссылка и будет вызываться parser_adt? Аргумент count_error просто для того, чтоб понимать когда появляются ошибки, он не принципиален, могу его объявлять внутри функции

2024-01-06 14:26 UTC, oltanik commented on olx_parser.py
> +            print(f'!!!!!!!!!!!!!!!!Объявление!!!!!!!!!!!!!!!!')
Хорошо, сделаю словарь и буду загружать его данными

2024-01-07 05:42 UTC, skeapskeap commented on olx_parser.py
> +def parser_adt(data, count_error):
Мне декомпозиция функции parser_page видится так:
```python
    for page_num in range(1, count):
        category_page_html = request_html(url=f'{url}{page_num}')
        adt_urls = extract_adt_urls(category_page_html)
        for adt_url in adt_urls:
            yield parse_adt(adt_url)
```
Ну и проверку title добавить.

2024-01-08 03:19 UTC, skeapskeap commented on olx_parser.py
> +def request_html(url):
эта функция должна возвращать html в виде строки, не объект bs

2024-01-08 03:19 UTC, skeapskeap commented on olx_parser.py
> +def extract_adt_urls(category_page_html):
эта функция сейчас ничего не возвращает, а должна

2024-01-08 03:19 UTC, skeapskeap commented on olx_parser.py
> +def parser_adt(adt_url):
На сколько понимаю, adt_url - это уже объект bs. Я предлагал сделать так, чтобы функция parser_adt принимала url обявления в виде строки, а внутри с помощью функции request_html получала html из этого url.

2024-01-10 05:29 UTC, skeapskeap requested changes

2024-01-10 05:29 UTC, skeapskeap commented on olx_parser.py
> +    url_divs = soup.find_all('div', class_='css-1sw7q4x').text
Тут скорее всего ошибка, у объекта, который возвращает find_all(), нет атрибута .text

2024-01-10 05:29 UTC, skeapskeap commented on olx_parser.py
>  if __name__ in '__main__':
```suggestion
if __name__ == '__main__':
```

2024-01-10 05:29 UTC, skeapskeap commented on olx_parser.py
> +    parser_page(url)
функция возвращает генератор, чтобы процесс парсинга пошел, по генератору надо итерироваться
```suggestion
    for adt_dict in parser_page(url):
        ...
```

2024-01-10 05:29 UTC, skeapskeap commented on olx_parser.py
> +    if int(date_time[0]):
Если правильно понял, это должна быть проверка того, что date_time[0] состоит из цифр. Оно так не работает, int('Сегодня') просто выкинет ValueError, и тогда на elif мы уже не попадём. Тут можно использовать метод str.isdigit()

2024-01-10 05:29 UTC, skeapskeap commented on olx_parser.py
> +    published_date = None
эти переменные можно на задавать здесь

2024-01-10 05:29 UTC, skeapskeap commented on olx_parser.py
> +        print(f'{"_"*51}error adt{"_"*51}')
Тут неплохо бы логировать информацию об ошибках, в идеале с трейсбэком, то есть используя logging. Да и в других местах тоже.
```suggestion
    except(requests.RequestException, ValueError, AttributeError) as err:
        logger.error(f'{"_"*51}error adt{"_"*51}',  exc_info=err)
```

2024-01-10 05:29 UTC, skeapskeap commented on olx_parser.py
>      date_of_last_visit = None
эти переменные не используются

2024-01-11 07:42 UTC, skeapskeap requested changes

2024-01-11 07:42 UTC, skeapskeap commented on olx_parser.py
> +        logging.error('error request_html', exc_info=err)
у модуля logging нет метода error(), его надо вызывать у объекта logger, который заранее где-то создаётся
```python
logger = logging.getLogger()
logger.error('error message')
```

2024-01-11 07:42 UTC, skeapskeap commented on olx_parser.py
> +    adv_html = BeautifulSoup(adv_html, 'lxml')
lxml это ошибка или так задумано?

2024-01-11 07:42 UTC, skeapskeap commented on olx_parser.py
> +    soup = BeautifulSoup(category_page_html, 'lxml')
lxml?

2024-01-13 03:43 UTC, skeapskeap requested changes

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +def translate_month_to_en(ru_month_name: str) -> str:
если переделать эту функцию так, чтобы она возвращала номер месяца, то можно сильно упростить остальной код
```suggestion
def translate_month_to_en(ru_month_name: str) -> int:
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +def parser_page(url):
функции принято называть глаголами
```suggestion
def parse_category(url):
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +        category_page_html = request_html(url=f'{url}{page_num}')
давай все таки проверку из extract_adt_urls() перенесём сюда, чтобы extract_adt_urls гарантированно всегда получала строку
```suggestion
        category_page_html = request_html(url=f'{url}{page_num}')
        if category_page_html is None:
            logger.error(f'error on request category page {page_num}')
            continue
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +        return adt_urls
```suggestion
def extract_adt_urls(category_page_html: str) -> list[str]:
    adt_urls = []
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +    return datetime.strptime(result, '%B, %Y')
вот для этого нужно сразу интовый месяц получать из translate_month_to_en
```suggestion
    dt_elements = date_time.split(' ')
    month = translate_month_to_en(dt_elements[2])
    year = int(dt_elements[3])
    return datetime(year, month, day=1)
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +        return datetime.strptime(date_of_last_visit, '%d, %B, %Y')
```suggestion
        day = int(date_time[1])
        month = translate_month_to_en(date_time[2])
        year = int(date_time[3])
        return datetime(year, month, day)
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +        return datetime.strptime(date_of_last_visit, '%d, %m, %Y %H:%M')
```suggestion
        hour, minute = date_time[2].split(':')
        date_of_last_visit = datetime.now().replace(hour=int(hour), minute=int(minute))
        return date_of_last_visit
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +        return datetime.strptime(date_of_last_visit, '%d, %m, %Y %H:%M')
```suggestion
        hour, minute = date_time[3].split(':')
        day_earlier = datetime.now() - timedelta(days=1)
        date_of_last_visit = day_earlier.replace(hour=int(hour), minute=int(minute))
        return date_of_last_visit
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +def parse_last_online_date(date_time: str) -> datetime:
Если ни один if не сработал, функция вернёт None. Это нормально если в БД будет лежать null в last_online_date? Может возвращать какое-то дефолтное значение? Или рейзить ошибку? Например если на сайте поменяется формат даты, об этом надо как-то узнать.

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
>          day = date_time[0]
```suggestion
        day = int(date_time[0])
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
>          year = date_time[2]
```suggestion
        year = int(date_time[2])
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +        return datetime.strptime(published_date, '%d %B %Y')
```suggestion
        published_date = datetime(year, month, day)
        return published_date
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
>          time = date_time[2]
```suggestion
        hour, minute = date_time[2].split(':')
```

2024-01-13 03:43 UTC, skeapskeap commented on olx_parser.py
> +        return datetime.strptime(published_date, '%d, %m, %Y %H:%M')
```suggestion
        published_date = datetime.now().replace(hour=int(hour), minute=int(minute))
        return published_date
```

2024-01-13 13:03 UTC, oltanik commented on olx_parser.py
> +def parser_page(url):
done

2024-01-13 13:06 UTC, oltanik commented on olx_parser.py
> +        category_page_html = request_html(url=f'{url}{page_num}')
done

2024-01-13 13:07 UTC, oltanik commented on olx_parser.py
> +        return adt_urls
done

2024-01-14 06:28 UTC, skeapskeap reviewed
ok

2024-01-14 12:13 UTC, skeapskeap approved these changes
надо мержить

2024-01-14 13:28 UTC, merged