migrations
SashaLesik/Learn_pyhton_site_clon pull request #13
Opened 2024-01-11 07:39 UTC by SashaLesik

2024-01-13 03:50 UTC, skeapskeap reviewed
В целом ок. Непонятно назначение файла runserver.py. Через него всегда будет запускаться приложение? Тогда надо оттуда убрать инсерт тестовых данных, делать это где-то отдульно.
Неплохо бы ещё добавить в README.md инфу, как запускать приложение в первый раз с пустой базой без таблиц.

2024-01-14 06:17 UTC, skeapskeap requested changes

2024-01-14 06:17 UTC, skeapskeap commented on web_app/__init__.py
> +        extract_from_db() #не уверена, что так делается
Вообще это правильная идея, вытащить логику работы с базой из вьюхи. Только сейчас результат выполнения этой функции никак не используется. И запрос внутри функции отличается от того, который здесь в 16 строчке.

2024-01-14 06:17 UTC, skeapskeap commented on web_app/__init__.py
> +        ads_list = OlxSite.query.order_by(OlxSite.date_posted.desc()).all()
Пока так норм. Когда объявления в БД станет много, нужно будет в запрос добавить, сколько строк хотим получать. Это можно будет сделать вместе с пагинацией.

2024-01-14 06:17 UTC, skeapskeap commented on web_app/database_functions.py
> +def parse_to_base(url, category, ads_name, ads_content, phone_number,
Договаривались, что эта функция будет принимать словарь. Формат словаря можно посмотреть в ветке olx_parse

2024-01-14 06:17 UTC, skeapskeap commented on web_app/database_functions.py
> +        parse_ad = OlxSite(category=category, ads_name=ads_name,
А тут будет просто распаковка словаря. И ещё тут надо бы ловить исключения, на случай если ключи словаря не соответствуют полям модели OlxSite.
```suggestion
        parse_ad = OlxSite(**ad_as_dict)
```

2024-01-14 06:17 UTC, skeapskeap commented on runserver.py
всё ещё не понятно назначение файла runserver.py

2024-01-14 07:41 UTC, SashaLesik commented on web_app/__init__.py
> +        extract_from_db() #не уверена, что так делается
@skeapskeap А можешь пояснить, что именно имешь в  виду? Почему не используется? И про запрос внутри в функци

2024-01-14 07:44 UTC, SashaLesik commented on runserver.py
@skeapskeap Можно ли тогда просто всё перенести в инит? 
if __name__ == "__main__":
    app = create_app()
    app.app_context().push()
    db.create_all()
    parse_to_base()

2024-01-15 20:13 UTC, merged