код для передвижения по страницам сайта
SashaLesik/Learn_pyhton_site_clon pull request #8
Opened 2023-12-19 10:56 UTC by oltanik

2023-12-19 11:49 UTC, skeapskeap reviewed
В целом подход рабочий, надо оформить в виде функции, которая на вход принимает url, и максимальное кол-во желаемых страниц. Возвращать должна iterable из html-страниц (str). Тут кстати хорошо зайдёт генератор, можно посмотреть мой пример с созвона.

2023-12-19 11:52 UTC, skeapskeap commented
И ещё надо в эту ветку вмержить main (именно так, не наоборот)

2023-12-20 12:45 UTC, skeapskeap commented on go_pages_olx.py
> +def go_pages(url, count=100):
Надо ещё добавить обработку исключений, если с запросом что-то случилось. Предусмотреть, что делать или если title не нашелся

2023-12-20 12:45 UTC, skeapskeap commented on go_pages_olx.py
> +        response = requests.get(f'{url}{page}')
тут нужен таймаут

2023-12-20 15:46 UTC, skeapskeap requested changes

2023-12-20 15:46 UTC, skeapskeap commented on go_pages_olx.py
> +            return False
Это значит, что функция вернёт false и завершится, даже если ошибка произошла только на одной из страниц. И ещё этот false нужно будет отлавливать в функции, вызывающей go_pages, чтобы не получить там ошибку из-за того, что у false нет методов/атрибутов объекта soup.
Короче я бы тут просто сделал continue

2023-12-29 15:40 UTC, skeapskeap requested changes

2023-12-29 15:40 UTC, skeapskeap commented on olx_parser.py
> +date = {'январь': 'January',
```suggestion
month_mapping = {'январь': 'January',
```
а ещё лучше будет получать значения из этого словаря через функцию
```python
def translate_month_to_en(ru_month_name: str) -> str:
    ...
```

2023-12-29 15:40 UTC, skeapskeap commented on olx_parser.py
> +def get_product(url, count = 100):
Сложно воспринимать такую длинную функцию и с такой вложенностью циклов. Давай разобьём на несколько:
1. парсинг категории
2. парсинг одной страницы в категории
3. парсинг одного объявления на странице

2023-12-29 15:40 UTC, skeapskeap commented on olx_parser.py
> +def format_date(date_time):
А пусть функция сама делает split, если уж она отвечает за парсинг даты.
```suggestion
def parse_date_string(date_string: str) -> datetime:
```

2023-12-29 15:47 UTC, skeapskeap commented on go_pages_olx.py
> +def go_pages(url, count=100):
Если правильно понял, эта функция больше не используется. Тогда можно удалить

2023-12-29 16:19 UTC, oltanik commented on go_pages_olx.py
> +def go_pages(url, count=100):
Удалил

2023-12-29 16:44 UTC, oltanik commented on olx_parser.py
> +def get_product(url, count = 100):
А мы же получается категории не парсим, берем просто одну категорию и парсим каждую страницу, а потом каждое объявление. Получается на две функции разбить? У нас просто в этой функции еще проверяется количество страниц всего в категории. Мы можем эту проверку вынести в отдельную функцию для более легкого восприятия еще и две функции по парсингу

2024-01-04 14:15 UTC, merged